print("\nDevelop a python program to split and join the string\n")
str1 = input("Enter a string : ")
print("Splitting of the string\n")
strList = str1.split(" ")
print("The splitted strings are ",strList)
print("\nJoining the strings \n")
str2 = " ".join(strList)
print("Joined string is \n",str2)